<?php
/**
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category   Dss
 * @package    Dss_ChangeCustomerPassword
 * @author     Extension Team
 * @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
 */
?>
<?php
    /** @var $block \Dss\ChangeCustomerPassword\Block\Adminhtml\Customer\PasswordChange */
?>
<?php if ($customerId = $block->getCustomerId()): ?>
    <div class="change-customer-pwd fieldset-wrapper">
        <div class="fieldset-wrapper-title">
            <strong class="title">
                <span><?= $escaper->escapeHtml(__('Change Password')); ?></span>
            </strong>
        </div>

        <div class="admin__fieldset-wrapper-content">
            <form action="<?= $escaper->escapeHtml(__($block->getUrl('customer/password/changePwdPost'))); ?>"
                method="post">
                <?= $block->getBlockHtml('formkey') ?>
            <input id="customer_id" type="hidden" name="customer_id"
                value="<?= $escaper->escapeHtml(__($customerId)); ?>" />
                <div class="admin__field">
                    <label class="admin__field-label">
                        <span><?= $escaper->escapeHtml(__('Enter Password')); ?></span>
                    </label>
                </div>
                <div class="admin__field-control">
                    <input class="admin__control-text"
                        type="password"
                        aria-label="<?= $escaper->escapeHtml(__('Password')) ?>"
                        name="new_customer_pwd"
                        style="width: 48%"
                        title="">
                </div>

                <div class="admin__field-control action">
                    <button id="save"
                            title="<?= $escaper->escapeHtml(__('Save Customer')) ?>"
                            type="submit"
                            class="action-scalable
                            save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
                            data-form-role="save"
                            data-ui-id="save-button"
                            role="button"
                            aria-disabled="false">
                        <span class="ui-button-text">
                            <span><?= $escaper->escapeHtml(__('Update Password')); ?></span>
                        </span>
                    </button>
                </div>
            </form>
        </div>
    </div>
<?php endif; ?>
